services:
  api1:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      MESSAGE: "${MESSAGE} - instancia 1"
    networks:
      - red_lab

  api2:
    build: ./api
    ports:
      - "3001:3000"
    environment:
      MESSAGE: "${MESSAGE} - instancia 2"
    networks:
      - red_lab

  api3:
    build: ./api
    ports:
      - "3002:3000"
    environment:
      MESSAGE: "${MESSAGE} - instancia 3"
    networks:
      - red_lab

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - datos_postgres:/var/lib/postgresql/data
    networks:
      - red_lab

volumes:
  datos_postgres:

networks:
  red_lab:
    driver: bridge